name: CI & Flyway Migration

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: poc_liq
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Récupération du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Lancer les migrations Flyway avec l'action officielle
      - name: Run Flyway migrations
        uses: devatherock/flyway-action@v3
        with:
          url: jdbc:mysql://mysql:3306/poc_liq
          user: root
          password: root
          locations: filesystem:./sql
          command: migrate