name: CI & Flyway Migration

on:
  push:
    branches: ["main"]

jobs:
  migrate:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: poc_liq
        ports:
          - 3306:3306
        options: >-
          --default-authentication-plugin=mysql_native_password
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flyway CLI
        run: |
          curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/11.12.0/flyway-commandline-11.12.0-linux-x64.tar.gz -o flyway.tar.gz
          tar -xzf flyway.tar.gz
          sudo ln -s $PWD/flyway-11.12.0/flyway /usr/local/bin/flyway

      - name: Flyway version
        run: flyway -v

      - name: Run Flyway migrations
        run: flyway -url=jdbc:mysql://localhost:3306/poc_liq -user=root -password=root -locations=filesystem:./sql migrate
